version: "3"

services:
  fuseki:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - fuseki_db:/fuseki/databases/imasdb
    environment:
      - FUSEKI_BASE=/fuseki
    restart: unless-stopped

volumes:
  fuseki_db:
